package org.umbrella.kie.api.definition.type;

import java.io.Externalizable;
import java.lang.annotation.Annotation;
import java.util.List;
import java.util.Map;

/**
 * FactType declarations are fact definitions (like classes) that
 * are managed alongside the rules.
 *
 * You then communicate with the KieBase by using instances created by this.
 *
 * There are utility set and get methods on this, as well as in the FactFields.
 *
 * The Object that is used is a javabean (which was generated by the engine).
 * You can also use reflection on it as normal.
 */
public interface FactType extends Externalizable{
    public String getName();

    public String getSimpleName();

    public String getPackageName();

    public String getSuperClass();

    public List<FactField> getFields();

    public FactField getField(String name);

    public Class<?> getFactClass();

    public Object newInstance() throws InstantiationException, IllegalAccessException;

    public void set(Object bean, String field, Object value);

    public Object get(Object bean, String field);

    public Map<String, Object> getAsMap(Object bean);

    public void setFromMap(Object bean, Map<String, Object> values);

    public List<Annotation> getClassAnnotations();

    public Map<String, Object> getMetaData();
}
