package org.umbrella.kie.api.event;

import org.umbrella.kie.api.runtime.KieRuntime;

/**
 * An event that is generated by the KIE runtime.
 */
public interface KieRuntimeEvent {
    /**
     * {@link org.umbrella.kie.api.runtime.KieRuntime} that generated the event.
     *
     * @return the KIE runtime
     */
    KieRuntime getKieRuntime();
}
