/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.umbrella.base;

import org.kie.api.KieServices;

public class Main {

    public static void main(String[] args) {
        KieServices kieServices = KieServices.Factory.get();
    }

}
